### ISSUE TITLE
Doubts about DeBruijn

### ISSUE THREAD

**Issue by joelsernamoreno** [gusgorman402/RFmoggy#1]
Hi!

Today I have seen RFMoggly and I have adapted the DeBruijn menu to work with ESP32.

After that I tested it but I find it strange how it works. 

When I choose some option in the DeBruijn menu and hit Submit, it only sends a signal. Then the code breaks and I have to reboot the device

Can you explain me how your DeBruijn code works? I have to change the debruijn_ten, debruijn_nine and debruijn_eight codes?

Thanks!

**Comment by gusgorman402** [comment]
I had a similar problem when developing. I think it might be a power issue.
I'm still understanding CC1101 buffers too. Try uncommenting Line 263
<https://github.com/gusgorman402/RFmoggy/blob/3f2f6067df581e6a4fb9b81e6ac4df8ed880ed7b/rfmoggy_wifiClientMode.ino#L263>
of the .ino file, this seemed to help during development. And having an
RTL-SDR for diagnostics helps too!

**Comment by gusgorman402** [comment]
If you have Telegram or Discord, I can be reached on there for quicker
help. I'll be making a YouTube video about the rfmoggy this month too

**Comment by joelsernamoreno** [comment]
Thank you for your response.

I have uncommented that line, but when I hit Submit it transmits the signal and then the web panel and the device crashes.

I have recorded an I/Q file. Can you check this? I have done the test with "Linear Multicode 10DIP 300MHz - 1033 length sequence"

Here you can download the file:

https://mega.nz/file/plI1CYRB#qmLDOP01_z2trwlRxVrCBrbH1j_ywlRaL0GncI_fjK8

Codification: 32-bit float
Sampling frequency: 2000000Hz

Thanks!

**Comment by joelsernamoreno** [comment]
Telegram: JoelSerna

**Comment by joelsernamoreno** [comment]
Btw... You can download and view my code here:

https://mega.nz/file/clAGGDiQ#pENPBy3_0qEwktKQyr_W3E04WEDBQSZy8Kmo1yrVmBU

If you want you can write me on telegram: @JoelSerna

Thanks!

**Comment by joelsernamoreno** [comment]
This works now. The problem is the setSpi function when you have two CC1101 modules. This is added to select a CC1101 module

Thanks
